### ISSUE TITLE
QgsMessageBar - přidat widget s tlačítkem pro zastavení

### ISSUE THREAD

**Issue by kalab-oto** [OpenGeoLabs/qgis-ndop-downloader#18]
Přidat do některých message barů widget s tlačítkem pro zastavení, to se může hodit pokud bude nějaký velký požadavek, který by trval dlouho.

**Comment by kalab-oto** [comment]
postup podle: https://docs.qgis.org/3.4/en/docs/pyqgis_developer_cookbook/communicating.html#

v QGIS python konzole funguje jak potřebuju:
```
from qgis.core import Qgis
def showError():
    iface.messageBar().clearWidgets()
    return iface.messageBar().pushMessage("Hotovo", "Zmáčknutí tlačítka", level=Qgis.Success)

widget = iface.messageBar().createMessage("Show","something")
button = QPushButton(widget)
button.setText("Zmáčkni")
button.pressed.connect(showError)
widget.layout().addWidget(button)
iface.messageBar().pushWidget(widget, Qgis.Warning)
```
v pluginu potom to stejné nefunguje `QPushButton` :
```
NameError: name 'QPushButton' is not defined 
Traceback (most recent call last):
  File "/home/kalab/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-ndop-downloader/ndop_downloader.py", line 268, in run
    mess_bar_butt("Stahování", "Dotazování databáze (odhadovaná doba: 1 minuta))", Qgis.Info, 0)
  File "/home/kalab/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis-ndop-downloader/ndop_downloader.py", line 251, in mess_bar_butt
    button = QPushButton(widget)
NameError: name 'QPushButton' is not defined
```

v kódu to mám připravené takto:
https://github.com/OpenGeoLabs/qgis-ndop-downloader/blob/3c91821044cef26b816dcdbf2a5fd11194caa194/ndop_downloader.py#L243-L256

**Comment by kalab-oto** [comment]
vyřešeno:
`from PyQt5.QtWidgets import QApplication, QWidget, QPushButton`

Nicméně to nebude fungovat jak bylo zamýšleno, protože po zobrazení zprávy se hned spustí funkce. Souvisí nejspíš i s https://github.com/OpenGeoLabs/qgis-ndop-downloader/issues/15.
